steps:
  shadowJar:
    image: "alpine"
    commands:
      - "apk update && apk add openjdk17"
      - "./gradlew licenseCheck shadowJar"

  setup-and-run-velocity:
    image: "alpine"
    commands:
      - "pwd"
      - "apk update && apk add curl openjdk17"
      - "mkdir -p velocity/plugins"
      - "ls -la"
      - "cp Plugin/build/libs/LibreLogin.jar velocity/plugins/"
      - "curl -sL https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/258/downloads/velocity-3.2.0-SNAPSHOT-258.jar -o velocity/velocity.jar"
      - "cd velocity"
      - "java -jar velocity.jar"

  publish:
    image: "alpine"
    commands:
      - "apk update && apk add openjdk17"
      - "./gradlew :API:publish -PkyngsRepoUsername=$${KYNGS_REPO_TOKEN} -PkyngsRepoPassword=$${KYNGS_REPO_SECRET}"
    when:
      - event: push
    secrets: [ kyngs_repo_token, kyngs_repo_secret ]

  update-wiki:
    image: "alpine"
    commands:
      - "apk update && apk add git"
      - "git clone https://github.com/kyngs/LibreLogin.wiki.git wiki"
      - "cd wiki"
      - "echo '```hocon' > Config.md && cat ../velocity/plugins/librelogin/config.conf >> Config.md && echo '```' >> Config.md"
      - "echo '```hocon' > Messages.md && cat ../velocity/plugins/librelogin/messages.conf >> Messages.md && echo '```' >> Messages.md"
      - "git config --local user.email 'kyngs@users.noreply.github.com'"
      - "git config --local user.name 'Kyngs CI (ci.kyngs.xyz)'"
      - "git add ."
      - "git diff-index --quiet HEAD || git commit -m 'Update configuration and messages on wiki' && git push https://kyngs:$${GITHUB_PERSONAL_TOKEN}@github.com/kyngs/LibreLogin.wiki.git"
    secrets: [ github_personal_token ]
    when:
      - event: push
        branch: master
