pipeline:
  shadowJar:
    image: "gradle:jdk17-focal"
    commands:
      - "gradle shadowJar"

  setup-velocity:
    image: "debian"
    commands:
      - "pwd"
      - "apt update && apt install -y curl"
      - "mkdir -p velocity/plugins"
      - "ls -la"
      - "cp Plugin/build/libs/LibreLogin.jar velocity/plugins/"
      - "curl -sL https://api.papermc.io/v2/projects/velocity/versions/3.1.2-SNAPSHOT/builds/184/downloads/velocity-3.1.2-SNAPSHOT-184.jar -o velocity/velocity.jar"

  run-velocity:
    image: "openjdk:17-jdk"
    directory: "velocity"
    commands:
      - "java -jar velocity.jar"

  checkout-wiki:
    image: "bitnami/git"
    commands:
      - "git clone https://github.com/kyngs/LibrePremium.wiki.git wiki"

  update-wiki:
    image: "debian"
    directory: "wiki"
    commands:
      - "echo '```hocon' > Config.md && cat ../velocity/plugins/librelogin/config.conf >> Config.md && echo '```' >> Config.md"
      - "echo '```hocon' > Messages.md && cat ../velocity/plugins/librelogin/messages.conf >> Messages.md && echo '```' >> Messages.md"

  commit-and-push-wiki:
    image: "bitnami/git"
    directory: "wiki"
    commands:
      - "git config --local user.email 'kyngs@users.noreply.github.com'"
      - "git config --local user.name 'kyngs'"
      - "git add ."
      - "git diff-index --quiet HEAD || git commit -m 'Update configuration and messages on wiki' && git push"
