name: Create configuration and update Wiki

on:
  push:
    branches:
      - master

jobs:
  build-and-create:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: 
          - chmod +x ./gradlew
        - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
        - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        - name: Shadow jar (build)
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: shadowJar
